//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedViolation
    {
        public int Id { get; set; }
        public int ServiceTypeId { get; set; }
        public int ViolationTypeId { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual ViolationType ViolationType { get; set; }
    }
}
