//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.RequiresModeration = false;
            this.EmailConfirmed = true;
            this.PhoneNumberConfirmed = true;
            this.TwoFactorEnabled = false;
            this.LockoutEnabled = false;
            this.AccessFailedCount = 0;
            this.IsDeleted = false;
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.Workers = new HashSet<Worker>();
            this.ServiceToClients = new HashSet<ServiceToClient>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Name { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public string PhoneNumber { get; set; }
        public string Skype { get; set; }
        public string Viber { get; set; }
        public string Website { get; set; }
        public string About { get; set; }
        public string FacebookProfile { get; set; }
        public string VkontakteProfile { get; set; }
        public Nullable<bool> RequiresModeration { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserId { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<int> Index { get; set; }
        public string Photo { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual PublicImage PublicImage { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
        public virtual ICollection<ServiceToClient> ServiceToClients { get; set; }
    }
}
