//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.SubDivisions = new HashSet<Division>();
            this.WorkPlaces = new HashSet<WorkPlace>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentDivisionId { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Division ParentDivision { get; set; }
        public virtual ICollection<Division> SubDivisions { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<WorkPlace> WorkPlaces { get; set; }
    }
}
