//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PralnaEntities : DbContext
    {
        public PralnaEntities()
            : base("name=PralnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PublicFile> PublicFiles { get; set; }
        public virtual DbSet<PublicImage> PublicImages { get; set; }
        public virtual DbSet<PublicVideo> PublicVideos { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<WorkPlace> WorkPlaces { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<ServiceToClient> ServiceToClients { get; set; }
        public virtual DbSet<ViolationType> ViolationTypes { get; set; }
        public virtual DbSet<AllowedViolation> AllowedViolations { get; set; }
        public virtual DbSet<FoundViolation> FoundViolations { get; set; }
    }
}
