//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicFile
    {
        public long Id { get; set; }
        public string OriginalName { get; set; }
        public string LocalFolder { get; set; }
        public string FolderForDownload { get; set; }
        public string FileName { get; set; }
        public long Size { get; set; }
        public string Description { get; set; }
        public string ParentId { get; set; }
        public Nullable<short> ResourceType { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> PublicVideoId { get; set; }
        public Nullable<bool> VideoConvertInProgress { get; set; }
    
        public virtual PublicVideo PublicVideo { get; set; }
    }
}
