//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicVideo
    {
        public PublicVideo()
        {
            this.PublicFiles = new HashSet<PublicFile>();
        }
    
        public int Id { get; set; }
        public string LocalFolder { get; set; }
        public string FolderForDownload { get; set; }
        public string ParentId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<short> ResourceType { get; set; }
        public string MpgName { get; set; }
        public string AviName { get; set; }
        public string ArchiveName { get; set; }
        public string Mp4Name { get; set; }
        public string OgvName { get; set; }
        public string WebmName { get; set; }
        public string MovName { get; set; }
        public string OriginalName { get; set; }
    
        public virtual ICollection<PublicFile> PublicFiles { get; set; }
    }
}
