//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.ProvidedServices = new HashSet<ServiceToClient>();
            this.AllowedViolations = new HashSet<AllowedViolation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> TimeLimit { get; set; }
        public Nullable<bool> UseTimeLimit { get; set; }
        public int WorkPlaceId { get; set; }
    
        public virtual WorkPlace WorkPlace { get; set; }
        public virtual ICollection<ServiceToClient> ProvidedServices { get; set; }
        public virtual ICollection<AllowedViolation> AllowedViolations { get; set; }
    }
}
