//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.ServicesToClients = new HashSet<ServiceToClient>();
        }
    
        public int Id { get; set; }
        public int WorkPlaceId { get; set; }
        public bool IsFormer { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual WorkPlace WorkPlace { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<ServiceToClient> ServicesToClients { get; set; }
    }
}
